# Copyright (c) 2025 河川(MrYzys)[https://github.com/MrYzys]
# Created: 2025-09-26
# License: AGPL-3.0-only (see LICENSE)
include: package:flutter_lints/flutter.yaml

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
